### ISSUE TITLE
investigate analytics

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/cosmos-discord-faucet#7]
- daily usage
- how many accounts are we servicing
- how many new accounts
- token depletion rate in faucet accounts

**Comment by dasanchez** [comment]
@uditvira two questions:
1. What do you have in mind for the delivery system? How about a (weekly?) report via bot in the `hypha:cosmos-monitoring` room?
2. How do we identify a new account? Would that just be a faucet "first time customer"?

**Comment by uditvira** [comment]
1. weekly digest in that cosmos monitoring room sounds perfect!
2. yes, first time faucet customer is what I was thinking

in terms of flow, thinking:
- [ ] make a monitoring/reporting plan by collecting thoughts and concerns in this issue for next couple weeks
  - what do we want to monitor and why (i've added a few thoughts towards this in my top level comment). my primary purpose is to get better insight into testnet usage
  - what's required from an engineering perspective to implement the monitoring
- [ ] make a feature list and prioritize some into a first sprint and spawn of tasks during our April 20th weekly call if we feel we are ready to move forward with any

**Comment by uditvira** [comment]
we could also make a grafana board for the faucet on monitor.polypore.xyz

**Comment by uditvira** [comment]
@ASoTNetworks any thoughts on what may be required for grafana or adding a weekly summary to our monitoring room on matrix?

**Comment by dasanchez** [comment]
An "estimated date to depletion" would be good too.

**Comment by dasanchez** [comment]
@ASoTNetworks and I talked about this today. We can make a Grafana dashboard on `monitor.polypore.xyz` that relies on node exporter in the bot droplet. This would require a bit of scripting on the bot machine besides the faucet itself.

## Features

* Dashboard
  * Theta/devnet selection
  * Plot: Requests vs time
  * Label: Total requests to date
  * Plot: Unique accounts vs time
  * Label: Total unique accounts to date
  * Plot: Faucet balance vs time
  * Label: Estimated date of faucet depletion

**Comment by dasanchez** [comment]
If we add the faucet balance to the transaction log every time a request is made, the log file will include everything we need for analytics.
